name: Terraform Automation
 
on:
  workflow_dispatch:  # Manual trigger
  push:
   branches: [main]
    
 
jobs:
  deploy:
    runs-on: ubuntu-latest
 
    env:
      #AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
      TF_VAR_client_id: "ce628383-4556-4e4d-9fac-cd90244c0c36"
      TF_VAR_client_secret: "Myk8Q~Fi_ogN6ca6.jxi.oJ_mcIKdeApRZ13Jaar"
      TF_VAR_subscription_id: "173133ca-1cba-49ee-9fa6-9643c8620098"
      TF_VAR_tenant_id: "429b7368-3c05-470a-9bc4-a7d1832236a2"
 
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
 
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.15.0
 
      - name: Configure Azure CLI
        run: az login --service-principal --username $TF_VAR_client_id --password $TF_VAR_client_secret --tenant $TF_VAR_tenant_id
 
      - name: Initialize Terraform
        run: terraform init --var-file=dev.tfvars
 
      - name: Terraform Plan
        run: terraform plan 
 
      - name: Terraform Apply
        run: terraform apply 
 
      - name: Clean up
        run: terraform destroy --var-file=dev.tfvars -auto-approve
